{{- if (or .Values.serviceAccount.create (eq .Values.serviceAccount.create nil)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-webserver.fullname" . }}
  labels:
    {{- include "my-webserver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}